service:
  name: job-hunt-diary-serverless
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello

resources:
  Resources:
    # Authentication with AWS Cognito User Pool
    UserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        Schema:
          - AttributeDataType: String
            Mutable: true
            Name: family_name # first name
            Required: true
          - AttributeDataType: String
            Mutable: true
            Name: given_name # last name
            Required: true
        UserPoolName: JobHuntDiaryUserPool
        UsernameAttributes:
          - email # User uses email address as username

    ApplicationTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: user_id # This is the user's email
            AttributeType: S
          - AttributeName: date_created
            AttributeType: S
          - AttributeName: company_name
            AttributeType: S
          - AttributeName: date_applied
            AttributeType: S
          - AttributeName: position_name
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        KeySchema: #required
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: date_created
            KeyType: RANGE
        TableName: jhd_applications
        GlobalSecondaryIndexes:
          - IndexName: jhd_application_byPosition
            Projection:
                ProjectionType: ALL
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH
              - AttributeName: position_name
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: jhd_application_byCompany
            Projection:
                ProjectionType: ALL
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH
              - AttributeName: company_name
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: jhd_application_byDateApplied
            Projection:
                ProjectionType: ALL
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH
              - AttributeName: date_applied
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
